---
stages:
  - .pre
  - build
  - .post
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 6

build-release-job:
  stage: build
  timeout: 30m
  image: duruyao/vimicro-mc:cpu-v0.9.5
  before_script:
    - TZ=UTC-8 date "+%Y-%m-%d %H:%M:%S"
  script:
    - python3 setup.py --help
    - python3 setup.py --build_type="release" --jobs="$(($(nproc) / 2))" --is_vc0768
  after_script:
    - TZ=UTC-8 date "+%Y-%m-%d %H:%M:%S"
  artifacts:
    paths:
      - build_*
